version: "3.7"

services:
  flask:
    image: maduee2/k8s-web:0.2
    deploy:
      mode: global
    ports: ["5000:5000"]

  test-node:
    image: maduee2/k8s-web:0.2
    deploy:
      replicas: 2
      placement:
        constraints: [node.role != manager]
    ports: ["5001:5000"]

  test-master:
    image: maduee2/k8s-web:0.2
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    ports: ["5002:5000"]
