apiVersion: v1
kind: Service
metadata:
  name: web-np
  labels:
    app: flask-web
spec:
  selector:
    app: flask-web
  ports:
    - name: np
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000
  type: NodePort
